name: ${project.name}
version: ${project.version}
api: "1.1.0"
author: Kredwi
main: ${plugin.main-class}
commands:
  clan:
    description: clan command
permissions:
  clan.use:
    description: base for use
    default: true
  clan.base:
    description: base
    default: true
  clan.admin:
    description: base
    default: op
